// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.25.0

package database

import (
	"database/sql"
	"time"

	"github.com/google/uuid"
)

type User struct {
	ID             uuid.UUID
	Firstname      string
	Lastname       sql.NullString
	Email          string
	Hashedpassword string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}
